apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-cleanup
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["config.flomesh.io"]
    resources: ["meshconfigs"]
    verbs: ["delete"]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "delete" ]
  - apiGroups: [ "app" ]
    resources: [ "deployments" ]
    verbs: [ "delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingressclasses" ]
    verbs: [ "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "delete", "update", "patch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [ "gateway.networking.k8s.io" ]
    resources: [ "gatewayclasses", "gateways" ]
    verbs: [ "get", "list", "create", "update", "patch", "delete" ]
  - apiGroups: [ "flomesh.io" ]
    resources: [ "namespacedingresses" ]
    verbs: [ "get", "list", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cleanup
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cleanup
    namespace: {{ include "fsm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-cleanup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cleanup
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cleanup
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-cleanup
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-cleanup
      restartPolicy: Never
      containers:
        # NOTE: The Helm post-delete hook's garbage-collector should always match the deletion logic in the fsm cli command `fsm uninstall cluster-wide-resources`.
        - name: garbage-collector
          image: "{{ include "fsmCRDs.image" . }}"
          imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
          # NOTE: any changes to resources being cleaned up should be updated in the lists/commands in the uninstall guide (https://github.com/flomesh-io/fsm-docs/blob/main/content/docs/guides/uninstall.md#uninstall-fsm-control-plane-and-remove-user-provided-resources) and the uninstall troubleshooting guide (https://github.com/flomesh-io/fsm-docs/blob/main/content/docs/guides/troubleshooting/uninstall.md)
          command:
            - sh
            - -c
            - >
             kubectl replace -f /fsm-crds;
             kubectl delete --ignore-not-found meshconfig -n '{{ include "fsm.namespace" . }}' fsm-mesh-config;
             kubectl delete --ignore-not-found secret -n '{{ include "fsm.namespace" . }}' {{ .Values.fsm.caBundleSecretName }};
             kubectl delete --ignore-not-found secret -n '{{ include "fsm.namespace" . }}' {{ .Values.fsm.remoteLogging.secretName }};
             kubectl delete secret -l flb.flomesh.io/config=true --ignore-not-found;
             kubectl delete --ignore-not-found meshrootcertificate -n '{{ include "fsm.namespace" . }}' fsm-mesh-root-certificate;
             kubectl delete mutatingwebhookconfiguration -l app.kubernetes.io/name=flomesh.io,app.kubernetes.io/instance={{ .Values.fsm.meshName }},app.kubernetes.io/version={{ .Chart.AppVersion }},app=fsm-injector --ignore-not-found;
             kubectl delete validatingwebhookconfiguration -l app.kubernetes.io/name=flomesh.io,app.kubernetes.io/instance={{ .Values.fsm.meshName }},app.kubernetes.io/version={{ .Chart.AppVersion }},app=fsm-controller --ignore-not-found;
             kubectl delete gatewayclasses.gateway.networking.k8s.io -l app.kubernetes.io/name=flomesh.io,app.kubernetes.io/instance={{ .Values.fsm.meshName }},app.kubernetes.io/version={{ .Chart.AppVersion }},app=fsm-gateway --ignore-not-found;
             kubectl delete gateways.gateway.networking.k8s.io -l app.kubernetes.io/name=flomesh.io,app.kubernetes.io/instance={{ .Values.fsm.meshName }},app.kubernetes.io/version={{ .Chart.AppVersion }},app=fsm-gateway --ignore-not-found;
             kubectl delete namespacedingresses.flomesh.io -l app.kubernetes.io/name=flomesh.io,app.kubernetes.io/instance={{ .Values.fsm.meshName }},app.kubernetes.io/version={{ .Chart.AppVersion }},app=fsm-ingress --ignore-not-found;
             kubectl delete ingressclasses pipy --ignore-not-found;
             kubectl delete deploy fsm-ingress -n '{{ include "fsm.namespace" . }}' --ignore-not-found;
             kubectl delete svc fsm-ingress -n '{{ include "fsm.namespace" . }}' --ignore-not-found;
{{- if .Values.fsm.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.fsm.imagePullSecrets | indent 8 }}
{{- end }}
      {{- if .Values.fsm.cleanup.affinity }}
      affinity:
      {{- toYaml .Values.fsm.cleanup.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.cleanup.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.fsm.cleanup.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.cleanup.tolerations }}
      tolerations:
      {{- toYaml .Values.fsm.cleanup.tolerations | nindent 8 }}
      {{- end }}

