{{- if .Values.fsm.cloudConnector.gateway.syncToFgw.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm-gateway-connector
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-gateway-connector
    meshName: {{ .Values.fsm.meshName }}
spec:
  {{- if not .Values.fsm.cloudConnector.autoScale.enable }}
  replicas: {{ .Values.fsm.cloudConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: fsm-gateway-connector
  template:
    metadata:
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
        app: fsm-gateway-connector
  {{- if .Values.fsm.cloudConnector.podLabels }}
  {{- toYaml .Values.fsm.cloudConnector.podLabels | nindent 8 }}
  {{- end }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9091'
    spec:
      {{- if .Values.fsm.cloudConnector.affinity }}
      affinity:
      {{- toYaml .Values.fsm.cloudConnector.affinity | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      serviceAccountName: {{ .Release.Name }}
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
      {{- include "restricted.securityContext" . | nindent 6 }}
      {{- end }}
      initContainers:
        - name: init-fsm-gateway-connector
          image: {{ .Values.fsm.curlImage }}
          command: ["curl", "http://fsm-bootstrap.{{ include "fsm.namespace" . }}.svc.cluster.local:9091/healthz", "--connect-timeout", "2", "--retry", "50", "--retry-connrefused", "--retry-delay", "5"]
      containers:
        - name: fsm-gateway-connector
          image: "{{ include "fsmConnector.image" . }}"
          imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
          ports:
            - name: "sidecar-inject"
              containerPort: 9090
            - name: "metrics"
              containerPort: 9091
          command: ['/fsm-connector']
          args: [
            "-verbosity", "{{.Values.fsm.controllerLogLevel}}",
            "-fsm-namespace", "{{ include "fsm.namespace" . }}",
            "-fsm-version", "{{ .Chart.AppVersion }}",
            "-mesh-name", "{{.Values.fsm.meshName}}",
            "-trust-domain", "{{.Values.fsm.trustDomain}}",
            "-sync-k8s-to-fgw={{.Values.fsm.cloudConnector.gateway.syncToFgw.enable}}",
            "-sync-k8s-to-fgw-default-sync={{.Values.fsm.cloudConnector.gateway.syncToFgw.defaultSync}}",
            {{- if .Values.fsm.cloudConnector.gateway.syncToFgw.allowK8sNamespaces }}
            {{- range .Values.fsm.cloudConnector.gateway.syncToFgw.allowK8sNamespaces }}
            "-sync-k8s-to-fgw-allow-k8s-namespaces={{ . }}",
            {{- end }}
            {{- end }}
            {{- if .Values.fsm.cloudConnector.gateway.syncToFgw.denyK8sNamespaces }}
            {{- range .Values.fsm.cloudConnector.gateway.syncToFgw.denyK8sNamespaces }}
            "-sync-k8s-to-fgw-deny-k8s-namespaces={{ . }}",
            {{- end }}
            {{- end }}
            "-via-gateway-ingress-ip-selector={{.Values.fsm.cloudConnector.gateway.ingress.ipSelector}}",
            "-via-gateway-ingress-http-port={{.Values.fsm.cloudConnector.gateway.ingress.httpPort}}",
            "-via-gateway-egress-http-port={{.Values.fsm.cloudConnector.gateway.egress.httpPort}}",
            "-via-gateway-ingress-grpc-port={{.Values.fsm.cloudConnector.gateway.ingress.grpcPort}}",
            "-via-gateway-egress-grpc-port={{.Values.fsm.cloudConnector.gateway.egress.grpcPort}}",
          ]
          resources:
            limits:
              cpu: "{{.Values.fsm.cloudConnector.resource.limits.cpu}}"
              memory: "{{.Values.fsm.cloudConnector.resource.limits.memory}}"
            requests:
              cpu: "{{.Values.fsm.cloudConnector.resource.requests.cpu}}"
              memory: "{{.Values.fsm.cloudConnector.resource.requests.memory}}"
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 9091
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 9091
          env:
            - name: CONTROLLER_SVC_NAME
              value: fsm-gateway-connector
            # The CONNECTOR_POD_NAME env variable sets pod name dynamically, used by fsm-gateway-connector to register events
            - name: CONNECTOR_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
    {{- if .Values.fsm.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.fsm.imagePullSecrets | indent 8 }}
    {{- end }}
      {{- if .Values.fsm.cloudConnector.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.fsm.cloudConnector.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.cloudConnector.tolerations }}
      tolerations:
      {{- toYaml .Values.fsm.cloudConnector.tolerations | nindent 8 }}
      {{- end }}
{{- end }}