{{- if .Values.fsm.cloudConnector.nacos.enable }}
apiVersion: v1
kind: Service
metadata:
  name: fsm-connector-nacos
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
    app: fsm-connector-nacos
spec:
  ports:
    - name: nacos-connector
      port: 9090
  selector:
    app: fsm-connector-nacos
{{- end }}