apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-preinstall
    namespace: {{ include "fsm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-preinstall
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-preinstall
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-preinstall
      labels:
        {{- include "fsm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-preinstall
      restartPolicy: Never
      containers:
        - name: preinstall
          image: "{{ include "fsmPreinstall.image" . }}"
          imagePullPolicy: {{ .Values.fsm.image.pullPolicy }}
          command: ['/fsm-preinstall']
          args:
            - --verbosity={{ .Values.fsm.controllerLogLevel }}
            - --enforce-single-mesh={{ .Values.fsm.enforceSingleMesh }}
            - --namespace={{ include "fsm.namespace" . }}
          resources:
            {{ toYaml .Values.fsm.preinstall.resources | indent 12 }}
{{- if .Values.fsm.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.fsm.imagePullSecrets | indent 8 }}
{{- end }}
      {{- if .Values.fsm.preinstall.affinity }}
      affinity:
      {{- toYaml .Values.fsm.preinstall.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.preinstall.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.fsm.preinstall.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fsm.preinstall.tolerations }}
      tolerations:
      {{- toYaml .Values.fsm.preinstall.tolerations | nindent 8 }}
      {{- end }}
